
DROP TABLE  CATEGORISATIONALBUM;
DROP TABLE  CATEGORISATIONFILM;
DROP TABLE  CATEGORISATIONPISTE;

DROP TABLE  CODECLOGICIEL;

DROP TABLE  CONTENUMULTIMEDIA;

DROP TABLE  CONTRIBUTIONFILM;
DROP TABLE  CONTRIBUTIONPISTE;

DROP TABLE  FICHIER;
DROP TABLE  FLUX;
DROP TABLE  URLEXTPHOTO;


DROP TABLE  CATEGORIEFILM;
DROP TABLE  CATEGORIEMUSIQUE;


DROP TABLE  PISTES;
DROP TABLE  ALBUM;
DROP TABLE  ARTIST;
DROP TABLE  FILM;

DROP TABLE  LANGUE;
DROP TABLE  CODEC;
DROP TABLE  LOGICIEL;

DROP TABLE  UTILISATEUR ;

DROP TABLE LANGUE;

DROP SEQUENCE idArtistSeq;
DROP SEQUENCE idFichierSeq;
DROP SEQUENCE idAlbumSeq;
DROP SEQUENCE NoFluxSeq;
DROP SEQUENCE NoPisteSeq;
